schemaVersion: "1.2"
endpoints:
    - name: appointments-8b1
      displayName: appointments
      service:
        basePath: /
        port: 8090
      type: REST
      networkVisibilities:
        - Project
        - Public
      schemaFilePath: openapi.yaml
dependencies:
    serviceReferences:
        - name: database:appdbDev
          connectionConfig: 01f00e13-21a3-1410-bf22-1d522470c14d
          env:
            - from: HostName
              to: DB_HOST
            - from: Port
              to: DB_PORT
            - from: Username
              to: DB_USER
            - from: Password
              to: DB_PASSWORD
            - from: DatabaseName
              to: DB_NAME
            - from: DatabaseNameTest
              to: DB_NAMETEST
